DataConvertible protocol, remove NSData references
IntrepidPursuits/swift-wisdom pull request #108
Opened 2017-02-03 16:33 UTC by paulrolfe

DataConvertible is an easy way to get from number types to Data and back. It could apply to UnsignedIntegers as well, but we already had the capability built in to them without the need for an optional initializer, so UnsignedIntegers actually don't technically conform to the protocol, although they have something very similar.

And I'd also like to remove all the `NSData` conveniences we built. I think everyone should have migrated to using `Data` by now. If this is too extreme to remove so much, I can hold off on that.

2017-02-03 17:46 UTC, paulrolfe commented on SwiftWisdom/Core/Foundation/Data/DataConvertible.swift
> +
I'll add a note that I borrowed this protocol from http://stackoverflow.com/questions/38023838/round-trip-swift-number-types-to-from-data

2017-02-03 21:09 UTC, alexpersian approved these changes
Looks good. Might be useful to get a 2nd opinion on the `NSData` removal.

2017-02-03 21:26 UTC, alexpersian requested changes
Fix failing tests.

2017-02-03 21:31 UTC, paulrolfe commented
retest this please

2017-02-06 17:52 UTC, alexpersian approved these changes

2017-02-06 17:59 UTC, bobgilmore commented
Are you cool not having a testpoint to exercise `ip_int8Value`? It's a pretty thin wrapper around `.to()` so I wouldn't be *crushed* if it's not exercised, but figured I'd point it out.

2017-02-06 18:04 UTC, brightredchilli commented
let's see how this one goes, but in the future, I think we should experiment with deprecating some versions before removing.

2017-02-06 18:05 UTC, brightredchilli approved these changes

2017-02-06 18:22 UTC, paulrolfe commented
@bob yeah might as well test it. Just added that.

2017-02-06 19:25 UTC, merged