Add Multicast protocol to implement multi-delegate systems.
IntrepidPursuits/swift-wisdom pull request #109
Opened 2017-02-09 23:10 UTC by elnoss

Lifted this from a current project 'cause I think it could be useful in other projects. This lets us quickly create classes that can have multiple delegates simply by conforming to `Multicast`.

2017-02-09 23:14 UTC, alexpersian commented on SwiftWisdom/Core/Multicast.swift
> +//  Created by Logan Wright on 9/4/15.
Logan made this?

2017-02-09 23:15 UTC, elnoss commented on SwiftWisdom/Core/Multicast.swift
> +//  Created by Logan Wright on 9/4/15.
Yeah, more or less. I only made slight modifications and added doc comments.

2017-02-10 12:44 UTC, paulrolfe approved these changes
:shipit:

2017-02-10 14:33 UTC, brightredchilli requested changes

2017-02-10 14:33 UTC, brightredchilli commented on SwiftWisdom/Core/CommonTypes/Multicast.swift
> +
lots of additional spaces between comments...did you mean to leave them in?

2017-02-10 14:33 UTC, brightredchilli commented on SwiftWisdomTests/CommonTypes/MulticastTests.swift
> +        if !messageRecipients.ip_contains(all: ["A", "B", "C"]) || messageRecipients.count != 3 {
I think we should prefer the positive assertion here - that messageRecipients contains those items, and the count is three.

2017-02-10 14:33 UTC, brightredchilli commented on SwiftWisdomTests/CommonTypes/MulticastTests.swift
> +        broadcaster.add(delegate: subscriberA)
I would also suggest that this particular test be broken out - this test should be named `testAddOnSameDelegateShouldNotReadd`. 

The overall test should be named `testBroadcastShouldBroadcastToAllDelegates`

2017-02-10 14:33 UTC, brightredchilli commented on SwiftWisdomTests/CommonTypes/MulticastTests.swift
> +        broadcaster.broadcast(that: "We are gorgeous")
love these messages.

2017-02-10 15:43 UTC, elnoss commented on SwiftWisdom/Core/CommonTypes/Multicast.swift
> +
Yeah, I don't mind deleting them but I thought it looked more readable

2017-02-10 19:55 UTC, brightredchilli approved these changes

2017-02-10 20:10 UTC, merged