Convert between UInt(16|32|64) and Data while respecting endianness
IntrepidPursuits/swift-wisdom pull request #113
Opened 2017-02-20 20:49 UTC by cprime

2017-02-21 13:50 UTC, paulrolfe requested changes
I like it. Not necessary for this PR, but maybe it should  also exist on signed Int16, 32, 64?

2017-02-21 13:50 UTC, paulrolfe commented on SwiftWisdomTests/Data/DataConversionTests.swift
> +        XCTAssert(data.ip_littleEndianUInt16Value == UInt16(1 << 8))
Can we also test when a nil should be returned in these?

2017-02-22 02:34 UTC, cprime commented
@paulrolfe I've added Int16, 32, 64 support as well

2017-02-22 15:20 UTC, paulrolfe approved these changes

2017-02-22 15:20 UTC, paulrolfe commented
retest this please

2017-02-23 02:00 UTC, cprime commented
retest this please

2017-02-27 15:41 UTC, paulrolfe commented
Looks like some tests need to be fixed.

2017-03-01 15:34 UTC, brightredchilli approved these changes

2017-03-01 15:34 UTC, brightredchilli commented on SwiftWisdom/Core/StandardLibrary/Numbers/Integer+Extensions.swift
> +    fileprivate var ip_data: Data {
I would rather see this as a Data constructor.

2017-03-01 15:34 UTC, brightredchilli commented
what was the change, ps?

2017-03-02 01:26 UTC, cprime commented on SwiftWisdom/Core/Foundation/Data/Data+Extensions.swift
> -        return self.withUnsafeBytes { $0.pointee }
These changes fixed the non-deterministic test failures

2017-03-02 01:27 UTC, cprime commented on SwiftWisdom/Core/StandardLibrary/Numbers/Integer+Extensions.swift
> +    fileprivate var ip_data: Data {
This is more inline with the `var ip_data: Data` on all of the other primitive types

2017-03-02 01:27 UTC, cprime commented on SwiftWisdom/Core/Foundation/Data/Data+Extensions.swift
> -        return self.withUnsafeBytes { $0.pointee }
@brightredchilli

2017-03-02 01:28 UTC, cprime commented on SwiftWisdom/Core/Foundation/Data/Data+Extensions.swift
> -        return self.withUnsafeBytes { $0.pointee }
no idea why

2017-03-23 03:11 UTC, cprime commented
retest this please

2017-03-23 14:10 UTC, cprime commented
retest this please

2017-03-23 14:13 UTC, merged