Add a Core-App-Extension-Safe subspec
IntrepidPursuits/swift-wisdom pull request #157
Opened 2018-10-02 17:00 UTC by bobgilmore

The code in UIApplication+Extensions.swift (with implicit references
to Application.shared) is not safe for use in a Today Widget.
Including it in a project with widgets generates...

EITHER the following compile-time warning:

ld: warning: linking against a dylib which is not safe for use in
application extensions: <path follows>

OR a compile time-error that the methods are marked unavailable,
depending on how Cocoapods generates the project files, especially
with regard to the "Require Only App-Extension-Safe API" setting.

A project has been creating a subspec in a separate branch, but as
it's of general utility, I'd like to move the subspec into the main
branch.

2018-10-02 17:51 UTC, MaxHasADHD approved these changes

2018-10-02 17:55 UTC, Benuuu commented
Related #104

2019-01-04 18:06 UTC, paulrolfe requested changes
Offline we decided to go with @bobgilmore's second proposal.
```
make the default spec EXTENSION-SAFE and add a subspecies to add the UIApplication bits
```

2019-01-15 18:29 UTC, bobgilmore commented
I’ve done some investigation. As far as I can tell, the separate specs (such as the various `stetson` branches maintain) are no longer needed.  Two things:
1. I’ve picked up vague hints that this was an iOS 8.0 and earlier SDK issue, and
2. On two separate occasions, months apart, I’ve successfully built my app AND its Today Extension using the “main” swift-wisdom branch. Hacks had to be made, because of some issues I won’t go into here, but the UIApplication / openURL issue was NOT one of them.

So my plan (for now) is to close this PR. If I’m way off base, I can always resurrect it.

2019-01-15 18:29 UTC, closed without merging