updated NSAttributedStrings
IntrepidPursuits/swift-wisdom pull request #74
Opened 2016-10-05 23:19 UTC by brightredchilli

2016-10-06 03:05 UTC, alexpersian requested changes
Big mixup on my part in regards to the `public` extension stuff. Sorry about that! Other than that just saw a couple things.

2016-10-06 03:05 UTC, alexpersian commented on SwiftWisdom/Core/StandardLibrary/NSAttributedString/NSMutableAttributedString+Format.swift
> +public extension NSMutableAttributedString {
I was wrong about this when we discussed it last week. After digging some more I found that extensions will inherit the access level of their type, but methods inside can set their own access level. So long as the functions we want accessible from outside are declared `public` we don't need this specifier. (based on [this link](https://www.andrewcbancroft.com/2015/04/22/3-nuances-of-swift-extensions/#extension-visibility) and [apple docs](https://developer.apple.com/library/ios/documentation/Swift/Conceptual/Swift_Programming_Language/AccessControl.html#//apple_ref/doc/uid/TP40014097-CH41-ID25))

I'll update my PR to reflect this as well.

2016-10-06 03:05 UTC, alexpersian commented on SwiftWisdom/Core/StandardLibrary/NSAttributedString/NSMutableAttributedString+Format.swift
> +fileprivate extension String {
Does this need to be moved if it's only being used in this file?

2016-10-06 03:05 UTC, alexpersian commented on SwiftWisdomTests/StandardLibrary/NSAttributedString/NSMutableAttributedString+FormatTests.swift
> +    func testExample() {
Can this be removed since it's just an example?

2016-10-06 12:40 UTC, brightredchilli commented on SwiftWisdom/Core/StandardLibrary/NSAttributedString/NSMutableAttributedString+Format.swift
> +public extension NSMutableAttributedString {
the doc says "If you extend a public or internal type, any new type members you add have a default access level of internal." - so I'm not actually so sure on this note. Let's not worry about this for now, just merge in your changes, we will test before a merge.

2016-10-06 12:41 UTC, brightredchilli commented on SwiftWisdomTests/StandardLibrary/NSAttributedString/NSMutableAttributedString+FormatTests.swift
> +    func testExample() {
yes absolutely

2016-10-06 12:41 UTC, brightredchilli commented on SwiftWisdom/Core/StandardLibrary/NSAttributedString/NSMutableAttributedString+Format.swift
> +fileprivate extension String {
I would like to make this public - but dont want to conflict with the work alan is doing. will take care of this before nyc/standard-library gets merged,  updating comment to do so

2016-10-06 13:49 UTC, alexpersian approved these changes

2016-10-08 20:04 UTC, Benuuu approved these changes

2016-10-08 20:04 UTC, Benuuu commented on SwiftWisdom/Core/StandardLibrary/NSAttributedString/NSMutableAttributedString+Format.swift
> +     - parameter args: comma separated list of arguments (NSAttributedString)
This line appears to be outdated.

2016-10-10 22:43 UTC, brightredchilli commented on SwiftWisdom/Core/StandardLibrary/NSAttributedString/NSMutableAttributedString+Format.swift
> +     - parameter args: comma separated list of arguments (NSAttributedString)
just had to rename the comment, fixed.

2016-10-10 22:48 UTC, merged